#!/bin/sh

set -ex

#######################################################################
# setup vagrant user
#######################################################################
chroot $target id vagrant >/dev/null 2>&1 || chroot $target useradd --create-home --uid 1000 --shell /bin/bash vagrant
mkdir -p $target/home/vagrant/.ssh
chmod 700 $target/home/vagrant/.ssh
cat > $target/home/vagrant/.ssh/authorized_keys << EOF
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
EOF
chmod 600 $target/home/vagrant/.ssh/authorized_keys
chroot $target chown -R vagrant:vagrant /home/vagrant/.ssh

#######################################################################
# setup passwordless sudo for vagrant user
#######################################################################
chroot $target apt-get install --yes sudo
cat > $target/etc/sudoers.d/vagrant <<EOF
vagrant ALL=(ALL) NOPASSWD:ALL
EOF
chmod 0440 $target/etc/sudoers.d/vagrant

#######################################################################
# setup resolvable hostname
#######################################################################
# hostname is the name of the release, as this was historically done
# on Vagrant images
if ifclass VAGRANTCONTRIB; then
	hostname="contrib-$release"
else
	hostname="$release"
fi

echo "$release" > $target/etc/hostname
sed -i "/127.0.0.1	localhost/a 127.0.0.2	$release" $target/etc/hosts

#######################################################################
# generate sshd host keys on first boot
#######################################################################
chroot $target systemctl enable generate-sshd-host-keys.service

#######################################################################
# Use traditional network interface names
#######################################################################
sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="net.ifnames=0 biosdevname=0"/' $target/etc/default/grub
chroot $target update-grub

#######################################################################
# set grub install device in debconf on first boot
#######################################################################
chroot $target systemctl enable set-grub-install-device.service

#######################################################################
# speed tweaks
#######################################################################

# Prevent DNS resolution (speed up logins)
echo "\n# debian vagrant box speedup\nUseDNS no" \
  >> $target/etc/ssh/sshd_config
