#!/usr/bin/python3
import subprocess
import sys
from os import environ, path

VERSIONS = {
    'buster': '10',
    'bullseye': 'testing',
    'testing': 'testing'  # allow access to testing via nickname and realname
}


def main():
    argcount = len(sys.argv)
    if argcount < 2 or argcount > 5 or not path.exists(sys.argv[1]):
        print(f"could not read box file", file=sys.stderr)
        sys.exit(1)

    rawdisk = sys.argv[1]
    namespace = 'debian-sandbox'
    if argcount >= 3:
        namespace = sys.argv[2]
    do_release = False
    if argcount == 4 and sys.argv[3] == 'do-release':
        do_release = True

    infos = parsedisk(rawdisk)
    version = buildversion(infos)
    upload_command = build_upload_command(rawdisk, infos, version,
                                          namespace, do_release)
    print(' '.join(upload_command))
    if 'VAGRANT_CLOUD_TOKEN' not in environ.keys():
        print('VAGRANT_CLOUD_TOKEN not set in environment, exiting')
        sys.exit(1)
    subprocess.check_call(upload_command, stdout=sys.stdout, stderr=sys.stderr)


def buildversion(infos):
    if not infos['dist'] in VERSIONS:
        raise ValueError(f"unknow distribution: {infos['dist']}")

    version = VERSIONS[infos['dist']]
    version += '.'
    if version == 'testing.':
        version = ''
    version += infos['builddate']
    version += '.'
    version += infos['buildincrement']
    return version


def parsedisk(boxname):
    filename = path.splitext(path.basename(boxname))[0]
    infos = filename.split('-')
    if len(infos) != 8:
        print(f"unable to parse boxname {boxname}", file=sys.stderr)
        sys.exit(1)

    info = {
        'hypervisor': infos[0],
        'os': infos[1],
        'dist': infos[2],
        'vendor': infos[3],  # vagrant or vagrant-contrib
        'arch': infos[4],
        'buildtype': infos[5],
        'builddate': infos[6],
        'buildincrement': infos[7],
    }

    return info


def build_upload_command(rawdisk, infos, version, namespace, do_release):
    # --force disables interactive confirmation prompt
    command = 'vagrant cloud publish --force'.split()
    if do_release:
        command.append('--release')

    box_name = infos['dist']
    box_name += '64'

    if infos['vendor'] == 'vagrantcontrib':
        box_name = 'contrib-' + box_name

    description = {
        'testing64': 'Debian "testing"',
        'bullseye64': 'Debian 11 "bullseye"',
        'buster64': 'Debian 10 "buster"',
        'contrib-buster64': 'Debian 10 "buster" with vboxsf contrib module for synced folders'
    }
    command.append('--short-description')
    command.append(description[box_name])

    command.append(namespace + '/' + box_name)
    command.append(version)
    command.append(infos['hypervisor'])
    command.append(rawdisk)
    return command


if __name__ == '__main__':
    main()
