name: Build & deploy Debian Vagrant images
run-name: ${{ github.actor }} is building ${{ github.repository }}
on: [workflow_dispatch, push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ca-certificates debsums dosfstools fai-server fai-setup-storage make python3 python3-libcloud python3-marshmallow python3-pytest python3-yaml sudo qemu-utils udev libguestfs-perl libxml-writer-perl uuid-runtime
          execute_install_scripts: true
          version: 1.0

      - name: Install makefile build deps
        run: make install-build-deps

      - name: Build Debian Stable image
        run: make build-libvirt-bookworm-vagrant-amd64
